#pragma once
#include <unordered_map>
#include <string>

// Filtered dvar descriptions - only dvars that exist in this game
// Original count: 1106
// Filtered count: 442
// Removed: 664

inline const std::unordered_map<std::string, std::string> dvar_descriptions = {
    {"r_sunblind_fadein", "time in seconds to fade blind from 0% to 100%"},
    {"g_player_maxhealth", "Player's maximum health"},
    {"r_sunflare_fadeout", "time in seconds to fade alpha from 100% to 0%"},
    {"ai_showVisDataDist", "Maximum distance for visibility data debugging information to be shown"},
    {"player_breath_gasp_lerp", "The interpolation rate for the target waver amplitude when gasping"},
    {"sv_cheats", "Turn on cheats: do not access directly - access through CheatsOk for server demo"},
    {"r_distortion", "Enable distortion"},
    {"r_sunglare_max_lighten", "0-1 fraction for how white the world is at max glare"},
    {"r_znear", "Things closer than this aren't drawn.  Reducing this increases z-fighting in the distance."},
    {"cl_freelook", "Enable looking with mouse"},
    {"ai_debugCoverEntityNum", "Display debug info for cover"},
    {"ui_bigFont", "Big font scale"},
    {"player_breath_hold_lerp", "The interpolation rate for the target waver amplitude when holding breath"},
    {"r_fullbright", "Toggles rendering without lighting"},
    {"bg_bobAmplitudeProne", "The multiplier to apply to the player's speed to get the bob amplitude while prone"},
    {"r_outdoorDownBias", "Affects the height map lookup for making sure snow doesn't go indoors"},
    {"r_vc_makelog", "Enable logging of light grid points for the vis cache.  1 starts from scratch, 2 appends."},
    {"com_maxfps", "Cap frames per second"},
    {"r_sunblind_fadeout", "time in seconds to fade blind from 100% to 0%"},
    {"sc_length", "Shadow cookie length"},
    {"r_mediumLodDist", "Distance for medium level of detail"},
    {"r_zfar", "Change the distance at which culling fog reaches 100% opacity; 0 is off"},
    {"developer", "Turn on Development systems"},
    {"bg_prone_yawcap", "The maximum angle that a player can look around quickly while prone"},
    {"developer_script", "Enable developer script comments"},
    {"cg_gun_x", "x position of the viewmodel"},
    {"hud_healthOverlay_phaseTwo_pulseDuration", "Pulse duration of the second health overlay phase"},
    {"com_statmon", "Draw stats monitor"},
    {"r_lightTweakSunDiffuseColor", "Sun diffuse color"},
    {"r_znear_depthhack", "Viewmodel near clip plane"},
    {"version", "Game version"},
    {"logfile", "Write to log file - 0 = disabled, 1 = async file write, 2 = Sync every write"},
    {"timescale", "Scale time of each frame"},
    {"fixedtime", "Use a fixed time rate for each frame"},
    {"sv_running", "Server is running"},
    {"cl_paused", "Pause the game"},
    {"com_introPlayed", "Intro movie has been played"},
    {"com_animCheck", "Check anim tree"},
    {"r_sunglare_max_angle", "angle from sun in degrees inside which glare is minimum"},
    {"r_specularMap", "Replace all specular maps with pure black (off) or pure white (super shiny)"},
    {"g_vehicleTexScrollScale", "Scale vehicle texture scroll scale by this amount (debug only)"},
    {"r_polygonOffsetScale", "Offset scale for decal polygons; bigger values z-fight less but poke through walls more"},
    {"ui_savegame", "Save game name"},
    {"r_sunsprite_shader", "name for static sprite; can be any material"},
    {"cg_gun_rot_rate", "The base weapon rotation rate"},
    {"r_sunsprite_size", "diameter in pixels at 640x480 and 80 fov"},
    {"r_sunflare_shader", "name for flare effect; can be any material"},
    {"mis_10", "Mission 10"},
    {"r_sunblind_min_angle", "angle from sun in degrees outside which blinding is 0"},
    {"cg_drawMantleHint", "Draw a 'press key to mantle' hint"},
    {"r_sunblind_max_darken", "0-1 fraction for how black the world is at max blind"},
    {"cg_errordecay", "Decay for predicted error"},
    {"r_drawWorld", "Enable world rendering"},
    {"r_lodBias", "Bias the level of detail distance (negative increases detail)"},
    {"r_sunflare_min_size", "smallest size of flare effect in pixels at 640x480"},
    {"r_sunflare_min_angle", "angle from sun in degrees outside which effect is 0"},
    {"r_vc_showlog", "Show this many rows of light grid points for the vis cache"},
    {"r_sunflare_max_size", "largest size of flare effect in pixels at 640x480"},
    {"r_sun_fx_position", "Position in degrees of the sun effect"},
    {"con_outputSliderColor", "Color of the console slider"},
    {"r_sunflare_max_angle", "angle from sun in degrees inside which effect is max"},
    {"r_singleCell", "Only draw things in the same cell as the camera.  Most useful for seeing how big the current cell is."},
    {"r_sunflare_max_alpha", "0-1 vertex color and alpha of sun at max effect"},
    {"r_drawPrimFloor", "Only draw primitive batches with more than this many triangles"},
    {"r_lightTweakAmbient", "Ambient light strength"},
    {"hud_deathQuoteFadeTime", "The time for the death quote to fade"},
    {"r_sunglare_fadeout", "time in seconds to fade glare from 100% to 0%"},
    {"r_sunflare_fadein", "time in seconds to fade alpha from 0% to 100%"},
    {"r_sunblind_max_angle", "angle from sun in degrees inside which blinding is max"},
    {"r_sunglare_min_angle", "angle from sun in degrees inside which glare is maximum"},
    {"cg_tracerScale", "Scale the tracer at a distance, so it's still visible"},
    {"r_sunglare_fadein", "time in seconds to fade glare from 0% to 100%"},
    {"r_ignore", "used for debugging anything"},
    {"safeArea_vertical", "Vertical safe area as a fraction of the screen height"},
    {"r_gamma", "Gamma value"},
    {"r_ignorehwgamma", "Ignore hardware gamma"},
    {"fx_visMinTraceDist", "Minimum visibility trace size"},
    {"cl_showmouserate", "Print mouse rate debugging information to the console"},
    {"r_lodScale", "Scale the level of detail distance (larger reduces detail)"},
    {"cg_hudGrenadePointerPulseMin", "The minimum alpha of the grenade indicator pulse. Values lower than 0 will cause the indicator to remain at full transparency for longer"},
    {"cg_bobWeaponRollAmplitude", "The amplitude of roll for weapon bobbing"},
    {"hud_health_startpulse_critical", "The health level at which to start the 'critical' pulse effect"},
    {"bg_foliagesnd_slowinterval", "The time between each foliage sound when moving slowly"},
    {"r_fog", "Set to 0 to disable fog"},
    {"cg_hudGrenadePointerPivot", "The pivot point of th grenade indicator pointer"},
    {"cg_hudGrenadeIconWidth", "The width of the grenade indicator icon"},
    {"mis_difficulty", "Mission difficulty"},
    {"r_skipPvs", "Skipt the determination of what is in the potentially visible set (disables most drawing)"},
    {"r_debugShader", "Enable shader debugging information"},
    {"r_polygonOffsetBias", "Offset bias for decal polygons; bigger values z-fight less but poke through walls more"},
    {"ai_debugFindPathDirect", "Display AI 'find direct path' debugging information"},
    {"cg_objectiveListWrapCountStandard", "The amount of on-screen length to wrap an objective in non wide-screen mode"},
    {"ai_debugFindPath", "Display AI 'find path' debugging information"},
    {"cl_avidemo", "AVI demo frames per second"},
    {"r_lightMap", "Replace all lightmaps with pure black or pure white"},
    {"r_colorMap", "Replace all color maps with pure black or pure white"},
    {"bg_foliagesnd_minspeed", "The speed that a player must be going to make minimum noise while moving through foliage"},
    {"r_normalMap", "Replace all normal maps with a flat normal map"},
    {"r_specularColorScale", "Set greater than 1 to brighten specular highlights"},
    {"r_showTris", "Show triangle outlines"},
    {"r_showTriCounts", "Triangle count for each rendered entity"},
    {"r_lightTweakSunLight", "Sunlight strength"},
    {"fx_enable", "Toggles all effects processing"},
    {"r_showSurfCounts", "Surface count for each rendered entity"},
    {"sc_enable", "Enable shadow cookies"},
    {"cg_cursorHints", "Draw cursor hints where:\n 0: no hints\n\t1:\tsin size pulse\n\t2:\tone way size pulse\n\t3:\talpha pulse\n\t4:\tstatic image"},
    {"r_showVertCounts", "Vertex count for each entity"},
    {"r_xdebug", "xmodel/xanim debug rendering"},
    {"ai_debugMayMove", "Display debug information for AI 'may move' calculations"},
    {"r_showLightGrid", "Show light grid debugging information"},
    {"cg_crosshairEnemyColor", "The crosshair color when over an enemy"},
    {"cg_footsteps", "Play footstep sounds"},
    {"r_showMissingLightGrid", "Use rainbow colors for entities that are outside the light grid"},
    {"r_lightTweakDiffuseFraction", "diffuse light fraction"},
    {"r_lightTweakAmbientColor", "Light ambient color"},
    {"r_lightTweakSunColor", "Sun color"},
    {"cl_forceavidemo", "Record AVI demo even if client is not active"},
    {"g_entinfo_scale", "Scale of the entity information text"},
    {"r_lightTweakSunDirection", "Sun direction in degrees"},
    {"cl_testAnimWeight", "test animation weighting"},
    {"r_logFile", "Write all graphics hardware calls for this many frames to a logfile"},
    {"cg_gun_y", "y position of the viewmodel"},
    {"mis_02", "Mission 2"},
    {"r_skipBackEnd", "Figure out what to draw, but don't actually draw it.  Useful for benchmarking."},
    {"r_norefresh", "Skips all rendering.  Useful for benchmarking."},
    {"loc_warningsAsErrors", "Throw an error for any unlocalized string"},
    {"jump_spreadAdd", "The amount of spread scale to add as a side effect of jumping"},
    {"r_smp_backend", "Process renderer back end in a separate thread"},
    {"mantle_check_angle", "The minimum angle from the player to a mantle surface to allow a mantle"},
    {"jump_ladderPushVel", "The velocity of a jump off of a ladder"},
    {"cg_gameBoldMessageWidth", "The maximum character width of the bold game messages"},
    {"r_drawPrimCap", "Only draw primitive batches with less than this many triangles"},
    {"fx_draw", "Toggles drawing of effects after processing"},
    {"cg_fov", "The field of view angle in degrees"},
    {"r_lowLodDist", "Distance for low level of detail"},
    {"player_deathInvulnerableTime", "The time that the player is invulnerable before dying"},
    {"mis_06", "Mission 6"},
    {"cg_hudGrenadeIconOffset", "The offset from the center of the screen for a grenade icon"},
    {"r_aaSamples", "Anti-aliasing sample count"},
    {"nextdemo", "The next demo to play"},
    {"r_clearColor", "Color to clear the screen to when clearing the frame buffer"},
    {"g_vehicleDebug", "Turn on debug information for vehicles"},
    {"r_clearColor2", "Color to clear every second frame to (for use during development)"},
    {"ui_multiplayer", "True if the game is multiplayer"},
    {"r_drawSun", "Enable sun effects"},
    {"r_drawEntities", "Enable entity rendering"},
    {"player_breath_gasp_time", "The amount of time a player will gasp once they can breath again"},
    {"player_healthEasy", "Player health on easy mode"},
    {"r_drawBModels", "Enable brush model rendering"},
    {"r_drawSModels", "Enable static model rendering"},
    {"r_drawXModels", "Enable xmodel rendering"},
    {"mis_09", "Mission 9"},
    {"r_dlightLimit", "Maximum number of dynamic lights drawn simultaneously"},
    {"sc_offscreenCasterLodBias", "Shadow cookie off-screen caster level of detail bias"},
    {"cg_gun_move_minspeed", "The minimum weapon movement rate"},
    {"r_sun_from_dvars", "Set sun flare values from dvars rather than the level"},
    {"cg_tracerchance", "The probability that a bullet is a tracer round"},
    {"player_breath_snd_lerp", "The interpolation rate for the player hold breath sound"},
    {"cg_gun_move_r", "Weapon movement right due to player movement"},
    {"r_lowestLodDist", "Distance for lowest level of detail"},
    {"g_earthquakeEnable", "Enable camera shake"},
    {"r_drawWater", "Enable water rendering"},
    {"r_lockPvs", "Lock the viewpoint used for determining what is visible to the current position and direction"},
    {"r_portalBevels", "Helps cull geometry by angles of portals that are acute when projected onto the screen, value is the cosine of the angle"},
    {"r_portalBevelsOnly", "Use screen-space bounding box of portals rather than the actual shape of the portal projected onto the screen"},
    {"loc_forceEnglish", "Force english localized strings"},
    {"ai_showBadPlaces", "Display debug information for 'bad places'"},
    {"r_portalWalkLimit", "Stop portal recursion after this many iterations.  Useful for debugging portal errors."},
    {"r_portalMinClipArea", "Don't clip child portals by a parent portal smaller than this fraction of the screen area."},
    {"cg_gun_ofs_f", "Forward weapon offset when prone/ducked"},
    {"r_showPortals", "Show portals for debugging"},
    {"r_showSModelNames", "Show static model names"},
    {"m_filter", "Allow mouse movement smoothing"},
    {"ai_corpseCount", "Maximum number of AI corpses"},
    {"ai_debugAnimDeltas", "Display animation delta debug information"},
    {"g_dumpAnims", "Write animation debug info for this entity"},
    {"r_showFbColorDebug", "Show front buffer color debugging information"},
    {"r_showFloatZDebug", "Show float z buffer used to eliminate hard edges on particles near geometry"},
    {"cg_brass", "Weapons eject brass"},
    {"ai_debugFindPathWidth", "Display paths with the given width"},
    {"hud_flash_period_offhand", "Offhand weapons flash period on changing weapon"},
    {"cg_hudGrenadePointerPulseFreq", "The number of times per second that the grenade indicator flashes in Hertz"},
    {"r_highLodDist", "Distance for high level of detail"},
    {"r_forceLod", "Force all level of detail to this level"},
    {"cg_crosshairAlpha", "The alpha value of the crosshair"},
    {"sc_blur", "Enable shadow cookie blur"},
    {"player_moveThreshhold", "The speed at which the player is considered to be moving for the purposes of \nview model bob and multiplayer model movement"},
    {"sc_count", "Number of shadow cookies"},
    {"fx_count", "Debug effects count"},
    {"sc_debugCasterCount", "Show debugging information for the shadow cookie caster count"},
    {"cg_hudGrenadePointerHeight", "The height of the grenade indicator pointer"},
    {"sc_debugReceiverCount", "Show debugging information for the shadow cookie receiver count"},
    {"bg_foliagesnd_maxspeed", "The speed that a player must be going to make maximum noise while moving through foliage"},
    {"sc_showOverlay", "Show shadow overlay for shadow cookies"},
    {"cg_centertime", "The time for a center printed message to fade"},
    {"ai_debugEntIndex", "Entity index of an entity to debug"},
    {"sc_showDebug", "Show debug information for shadow cookies"},
    {"sc_wantCount", "Number of desired shadows"},
    {"sc_wantCountMargin", "Margin of error on number of desired shadows"},
    {"sc_fadeRange", "Shadow cookie fade range"},
    {"sv_saveOnStartMap", "Save at the start of a level"},
    {"cg_gun_z", "z position of the viewmodel"},
    {"sc_shadowInRate", "Rate at which the shadow cookie horizon moves inwards"},
    {"sc_shadowOutRate", "Rate at which the shadow cookie horizon moves outwards"},
    {"sc_offscreenCasterLodScale", "Shadow cookie off-screen caster level of detail scale"},
    {"hud_health_pulserate_injured", "The pulse rate of the 'injured' pulse effect"},
    {"cl_noprint", "Print nothing to the console"},
    {"cg_gameMessageWidth", "The maximum character width of the game messages"},
    {"cg_crosshairDynamic", "Crosshair is Dynamic"},
    {"snd_stereo", "Sets whether to use stereo or mono"},
    {"r_blur", "Dev tweak to blur the screen"},
    {"r_glow", "Enable glow."},
    {"ai_showNearestNode", "Show nodes closest to AI"},
    {"g_gravity", "Gravity in inches per second per second"},
    {"cl_shownet", "Display network debugging information"},
    {"cg_drawBreathHint", "Draw a 'hold breath to steady' hint"},
    {"g_weaponAmmoPools", "Use pooled ammunition for weapons"},
    {"snd_enableReverb", "Enable sound reverberation"},
    {"ai_moveOrientMode", "Debug AI Orient Mode"},
    {"mantle_view_yawcap", "The angle at which to restrict a sideways turn while mantling"},
    {"g_no_script_spam", "Turn off script debugging information"},
    {"r_outdoorAwayBias", "Affects the height map lookup for making sure snow doesn't go indoors"},
    {"player_deathInvulnerableToMelee", "The player is invulnerable to melee attacks during death invulnerability"},
    {"g_entinfo_maxdist", "Maximum distance of an entity from the camera at which to show entity information"},
    {"r_outdoorFeather", "Outdoor z-feathering value"},
    {"cg_tracerlength", "The length of a tracer round"},
    {"cg_hudStanceFlash", "The background color of the flash when the stance changes"},
    {"inertiaMax", "Maximum player inertia"},
    {"mapname", "current map name"},
    {"ai_showPotentialThreatDir", "Display AI potential threat direction"},
    {"bg_aimSpreadMoveSpeedThreshold", "When player is moving faster than this speed, the aim spread will increase"},
    {"ai_playerNearRange", "Maximum range for AI to use 'near' accuracy"},
    {"ui_smallFont", "Small font scale"},
    {"monkeytoy", "Restrict console access"},
    {"cg_drawFPS", "Draw frames per second"},
    {"g_drawGrenadeHints", "Draw debug information for grenades"},
    {"bg_bobAmplitudeStanding", "The multiplier to apply to the player's speed to get the bob amplitude while standing"},
    {"inertiaDebug", "Show inertia debug information"},
    {"player_meleeHeight", "The height of the player's melee attack"},
    {"con_inputBoxColor", "Color of the console input box"},
    {"hud_healthOverlay_phaseOne_toAlphaAdd", "Alpha value to add to the first health overlay phase"},
    {"player_strafeSpeedScale", "The scale applied to the player speed when strafing"},
    {"jump_stepSize", "The maximum step up to the top of a jump arc"},
    {"ai_showVisData", "Display debug information for visibility data"},
    {"cl_stanceHoldTime", "The time to hold the stance button before the player goes prone"},
    {"con_outputWindowColor", "Color of the console output"},
    {"loc_language", "Language"},
    {"loc_translate", "Enable translations"},
    {"loc_warnings", "Enable localization warnings"},
    {"ai_debugGrenadeHintArc", "Grenade hint arc in degrees"},
    {"hud_fade_stance", "The time for the stance to fade in seconds"},
    {"player_healthHard", "Player health in challenging mode"},
    {"sv_lastSaveGame", "Last save game file name"},
    {"cl_analog_attack_threshold", "The threshold before firing"},
    {"cg_tracerScaleMinDist", "The minimum distance to scale a tracer"},
    {"bg_bobAmplitudeDucked", "The multiplier to apply to the player's speed to get the bob amplitude while ducking"},
    {"shortversion", "Short game version"},
    {"cg_drawHUD", "Draw HUD elements"},
    {"fx_freeze", "Freeze effects"},
    {"hud_healthOverlay_phaseThree_pulseDuration", "Pulse duration of the third health overlay phase"},
    {"cg_hudGrenadeIconMaxHeight", "The minimum height difference between a player and a grenade for the grenade to be shown on the grenade indicator"},
    {"ui_extraBigFont", "Extra large font scale"},
    {"mantle_check_radius", "The player radius to test against while mantling"},
    {"mis_03", "Mission 3"},
    {"g_gameskill", "Game skill level"},
    {"con_miniconlines", "Number of lines in the minicon message window"},
    {"player_healthMedium", "Player health in medium mode"},
    {"player_healthFu", "Player health in veteran mode"},
    {"cg_hintFadeTime", "Time in milliseconds for the cursor hint to fade"},
    {"nextmap", "The next map name"},
    {"g_reloading", "True if the game is reloading"},
    {"m_side", "Sideways motion in units per second"},
    {"safeArea_horizontal", "Horizontal safe area as a fraction of the screen width"},
    {"cg_gun_ofs_r", "Right weapon offset when prone/ducked"},
    {"g_vehicleDrawPath", "Turn on debug information for vehicle paths"},
    {"hud_healthOverlay_phaseTwo_toAlphaMultiplier", "Alpha multiplier for the second health overlay phase"},
    {"cg_drawHealth", "Draw health bar"},
    {"snd_enable2D", "Enable 2D sounds"},
    {"m_yaw", "Default yaw"},
    {"hud_fade_ammodisplay", "The time for the ammo display to fade in seconds"},
    {"hud_fade_healthbar", "The time for the health bar to fade in seconds"},
    {"cl_freemove", "Fly about the level"},
    {"sensitivity", "Mouse sensitivity"},
    {"hud_healthOverlay_pulseStop", "The percentage of full health above which the health overlay fades out"},
    {"cl_yawspeed", "Max yaw speed in degrees for game pad and keyboard"},
    {"mis_08", "Mission 8"},
    {"cg_tracerScaleDistRange", "The range at which a tracer is scaled to its maximum amount"},
    {"cl_pitchspeed", "Max pitch speed in degrees for game pad"},
    {"r_inGameVideo", "Allow in game cinematics"},
    {"cl_anglespeedkey", "Multiplier for max angle speed for gamepad and keyboard"},
    {"cl_mouseAccel", "Mouse acceleration"},
    {"m_pitch", "Default pitch"},
    {"g_useholdtime", "The time to hold down the 'use' button to activate a 'use' command"},
    {"m_forward", "Forward speed in units per second"},
    {"cg_drawCrosshair", "Turn on weapon crosshair"},
    {"ai_showNodesDist", "Maximum distance from the camera at which AI nodes are shown"},
    {"g_knockback", "Maximum player knockback"},
    {"cg_subtitles", "Turn on subtitles"},
    {"ai_debugCoverSelection", "Enable debugging information for cover selection"},
    {"cg_hudStanceHintPrints", "Draw helpful text to say how to change stances"},
    {"cg_blood", "Show blood effects"},
    {"ai_playerFarAccuracy", "Accuracy for AI far away from the player"},
    {"mis_none", "No mission"},
    {"g_friendlyNameDist", "Maximum distance at which a friendly name shows when the crosshairs is over them"},
    {"mis_01", "Mission 1"},
    {"mis_04", "Mission 4"},
    {"mis_05", "Mission 5"},
    {"cg_gun_rot_minspeed", "The minimum weapon rotation speed"},
    {"ai_showClaimedNode", "Show claimed node debugging information"},
    {"g_speed", "Maximum player speed"},
    {"mis_07", "Mission 7"},
    {"con_inputHintBoxColor", "Color of the console input hint box"},
    {"con_outputBarColor", "Color of the console output slider bar"},
    {"mantle_check_range", "The minimum distance from a player to a mantle surface to allow a mantle"},
    {"ai_debugGrenadeFailSafe", "Display grenade fail safe debug information"},
    {"con_typewriter_printspeed", "Time (in milliseconds) to print each letter in the line."},
    {"con_minicontime", "Onscreen time for minicon messages in seconds"},
    {"bg_foliagesnd_fastinterval", "The time between each foliage sound when moving quickly"},
    {"player_meleeWidth", "The width of the player's melee attack"},
    {"hud_healthOverlay_phaseEnd_pulseDuration", "Pulse duration of the final health overlay phase"},
    {"snd_errorOnMissing", "Cause a Com_Error if a sound file is missing."},
    {"snd_khz", "The game sound frequency."},
    {"snd_bits", "The game sound bit rate."},
    {"snd_volume", "Game sound master volume"},
    {"snd_slaveFadeTime", "The amount of time in milliseconds for a 'slave' sound\nto fade its volumes when a master sound starts or stops"},
    {"snd_enable3D", "Enable 3D sounds"},
    {"g_drawEntBBoxes", "Draw entity bounding boxes"},
    {"cg_gun_move_rate", "The base weapon movement rate"},
    {"snd_enableStream", "Enable streamed sounds"},
    {"ui_mousePitch", "Invert mouse pitch"},
    {"ui_campaign", "The current campaign"},
    {"ui_nextMission", "Next mission"},
    {"cg_debugevents", "Output event debug information"},
    {"ui_autoContinue", "Automatically 'click to continue' after loading a level"},
    {"hud_healthOverlay_phaseThree_toAlphaMultiplier", "Alpha multiplier for the third health overlay phase"},
    {"cg_drawpaused", "Draw paused screen"},
    {"gamename", "The name of the game"},
    {"gamedate", "The date compiled"},
    {"sv_mapname", "The current map name"},
    {"g_ai", "Enable AI"},
    {"player_adsExitDelay", "Delay before exiting aim down sight"},
    {"g_spawnai", "Enable AI spawning"},
    {"ai_noDodge", "AI won't dodge to the side"},
    {"ai_playerNearAccuracy", "Accuracy for an AI near to a player"},
    {"cg_small_dev_string_fontscale", "Font scale for a small development only display string"},
    {"ai_playerFarRange", "Minimum range for AI to use 'far' accuracy"},
    {"bg_foliagesnd_resetinterval", "The time interval before foliage sounds are reset after the player has stopped moving"},
    {"cg_invalidCmdHintDuration", "Duration of an invalid command hint"},
    {"hud_fadeout_speed", "The speed that the HUD will fade at"},
    {"ai_debugFindPathLock", "Find path lock"},
    {"g_playerTrailTime", "Time for player 'trail' for AI missing"},
    {"ai_disableSpawn", "Do not spawn AI"},
    {"g_changelevel_time", "Time for change level fade out"},
    {"g_debugLocDamage", "Display locational damage debug information"},
    {"g_friendlyfireDist", "Maximum distance at which the player channot shoot while the crosshair is over a friendly"},
    {"cg_hudGrenadePointerPulseMax", "The maximum alpha of the grenade indicator pulse. Values higher than 1 will cause the indicator to remain at full brightness for longer"},
    {"inertiaAngle", "The cosine of the angle at which inertia occurs"},
    {"player_view_pitch_up", "Maximum angle that the player can look up"},
    {"player_view_pitch_down", "Maximum angle that the player can look down"},
    {"bg_ladder_yawcap", "The maximum angle that a player can look around while on a ladder"},
    {"bg_fallDamageMinHeight", "The height that a player will start to take minimum damage if they fall"},
    {"bg_fallDamageMaxHeight", "The height that a player will take maximum damage when falling"},
    {"friction", "Player friction"},
    {"stopspeed", "The player deceleration"},
    {"bg_swingSpeed", "The rate at which the player's legs swing around when strafing(multi-player only)"},
    {"cg_drawScriptUsage", "Draw debugging information for scripts"},
    {"bg_bobMax", "The maximum allowed bob amplitude"},
    {"player_breath_hold_time", "The maximum time a player can hold his breath"},
    {"player_breath_fire_delay", "The amount of time subtracted from the player remaining breath time when a weapon is fired"},
    {"player_breath_gasp_scale", "Scale value to apply to the target waver during a gasp"},
    {"player_breath_snd_delay", "The delay before playing the breathe in sound"},
    {"player_scopeExitOnDamage", "Exit the scope if the player takes damage"},
    {"player_footstepsThreshhold", "The minimum speed at which the player makes loud footstep noises"},
    {"cg_gun_rot_r", "Gun roll rotation with movement"},
    {"cg_hudGrenadeIconInScope", "Show the grenade indicator when aiming down the sight of a scoped weapon"},
    {"player_backSpeedScale", "The scale applied to the player speed when moving backwards"},
    {"player_spectateSpeedScale", "The scale applied to the player speed when spectating"},
    {"player_turnAnims", "Use animations to turn a player's model in multiplayer"},
    {"mantle_enable", "Enable player mantling"},
    {"cg_drawGun", "Draw the view model"},
    {"fx_debugBolt", "Debug effects bolt"},
    {"player_meleeRange", "The maximum range of the player's mellee attack"},
    {"jump_height", "The maximum height of a player's jump"},
    {"cg_hudDamageIconTime", "The amount of time for the damage icon to stay on screen after damage is taken"},
    {"jump_slowdownEnable", "Slow player movement after jumping"},
    {"cg_viewVehicleInfluence", "The influence on the view from being in a vehicle"},
    {"mantle_debug", "Show debug information for mantling"},
    {"g_debugDamage", "Turn on debug information for damage"},
    {"g_debugBullets", "Turn on debug information for bullets"},
    {"g_listEntity", "list all of the current entities"},
    {"g_entinfo", "Display entity information"},
    {"g_deathDelay", "Delay a level restart on death"},
    {"ai_showNodes", "Show AI navigation node debug information"},
    {"ai_showFriendlyChains", "Display debug information for friendly chains"},
    {"cg_dumpAnims", "Output animation info for the given entity id"},
    {"ai_showDodge", "Display debug information for AI dodging"},
    {"ai_showPaths", "Show AI navigation paths"},
    {"ai_ShowCanshootChecks", "Display debugging information for 'can shoot' checks"},
    {"ai_badPathSpam", "Write debugging information for a bad AI paths"},
    {"ai_debugThreatSelection", "Enable debugging information for threat selection"},
    {"ai_showRegion", "Draw all the cover in a volume for debugging"},
    {"g_dumpAnimsCommands", "Write animation commands debug info for this entity"},
    {"cg_draw2D", "Draw 2D screen elements"},
    {"cg_tracerSpeed", "The speed of a tracer round in units per second"},
    {"cg_drawMaterial", "Draw debugging information for materials"},
    {"cg_drawTurretCrosshair", "Draw a cross hair when using a turret"},
    {"cg_hudDamageIconWidth", "The width of the damage icon"},
    {"cg_hudDamageIconHeight", "The height of the damage icon"},
    {"cg_hudDamageIconOffset", "The offset from the center of the damage icon"},
    {"cg_hudDamageIconInScope", "Draw damage icons when aiming down the sight of a scoped weapon"},
    {"cg_hudGrenadeIconHeight", "The height of the grenade indicator icon"},
    {"cg_hudGrenadePointerWidth", "The width of the grenade indicator pointer"},
    {"cg_weaponCycleDelay", "The delay after cycling to a new weapon to prevent holding down the cycle weapon button from cycling too fast"},
    {"cg_crosshairAlphaMin", "The minimum alpha value of the crosshair when it fades in"},
    {"cg_gun_move_f", "Weapon movement forward due to player movement"},
    {"cg_gun_move_u", "Weapon movement up due to player movement"},
    {"hud_healthOverlay_phaseEnd_fromAlpha", "Starting alpha of the final health overlay phase"},
    {"cg_gun_ofs_u", "Up weapon offset when prone/ducked"},
    {"cg_gun_rot_p", "Pitch gun rotation with movement"},
    {"cg_gun_rot_y", "Yaw gun rotation with movement"},
    {"cg_bobWeaponAmplitude", "The weapon bob amplitude"},
    {"cg_bobWeaponMax", "The maximum weapon bob"},
    {"cg_bobWeaponLag", "The lag on the weapon bob"},
    {"cg_nopredict", "Don't do client side prediction"},
    {"cg_showmiss", "Show prediction errors"},
    {"con_minicon", "Display the mini console on screen"},
    {"cg_tracerwidth", "The width of the tracer round"},
    {"cg_objectiveListWrapCountWidescreen", "The amount of on-screen length to wrap an objective in wide-screen mode"},
    {"cg_subtitleMinTime", "The minimum time that the subtitles are displayed on screen in seconds"},
    {"cg_subtitleWidthStandard", "The width of the subtitles on a non wide-screen"},
    {"cg_subtitleWidthWidescreen", "The width of the subtitle on a wide-screen"},
    {"hud_health_pulserate_critical", "The pulse rate of the 'critical' pulse effect"},
    {"hud_healthOverlay_phaseEnd_toAlpha", "Final alpha of the final health overlay phase"},
    {"hud_flash_time_offhand", "Offhand weapons flash duration on changing weapon"},
    {"cg_invalidCmdHintBlinkInterval", "Blink rate of an invalid command hint"},
    {"fx_profile", "Turn on FX profiling"},
    {"hud_fade_offhand", "The time for the offhand weapons to fade in seconds"},
    {"hud_fade_compass", "The time for the compass to fade in seconds"},
    {"hud_health_startpulse_injured", "The health level at which to start the 'injured' pulse effect"},
    {"hud_healthOverlay_pulseStart", "The percentage of full health at which the low-health warning overlay begins flashing"},
    {"hud_healthOverlay_phaseOne_pulseDuration", "Pulse duration of the first health overlay phase"},
    {"RunForTime", "Time for the server to run"}
};
